[package]
name = "rs-vulkan"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bevy_math = "0.15.3"
bytemuck = "1.22.0"
env_logger = "0.11.8"
log = "0.4.27"
nanorand = "0.7.0"
pollster = "0.4.0"
tobj = "4.0.3"
wgpu = "24.0.3"
winit = "0.30.9"

[dependencies.image]
version = "0.25.6"
default-features = false
features = ["png", "jpeg"]
