[package]
name = "rs-vulkan"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_math = "0.15.3"
bytemuck = "1.22.0"
env_logger = "0.11.7"
gltf = "1.4.1"
log = "0.4.27"
nanorand = "0.7.0"
pollster = "0.4.0"
tobj = "4.0.3"
wgpu = "24.0.3"
winit = "0.30.9"
