[package]
name = "wre_window"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
pollster = "0.4.0"
log = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
wre_world = { path = "../wre_world" }
