[package]
name = "wre_model"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
tobj = "4.0.3"
image = { version = "0.25.6", default-features = false, features = [
    "jpeg",
    "png",
] }
glam = { workspace = true }
thiserror = { workspace = true }
