[package]
name = "wre_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
ash.workspace = true
winit = { workspace = true }
thiserror.workspace = true
ash-bootstrap = "0.1.3"
ash-window = "0.13.0"
vk-mem = "0.5.0"
